---
- name: Converge
  hosts: all
  tasks:
    - name: "Include nginx-proxy"
      include_role:
        name: "nginx-proxy"

  vars:
    nginx_remove_default_vhost: true
    nginx_vhosts:
      - server_name: "test.dev"
        root: "/var/www/test"

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false