---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    #image: docker.io/pycontribs/centos:7
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    # Note: the below cmd is critical for systemd and jeff's base image
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
